# Generated by Django 4.0.3 on 2022-03-22 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='steps',
        ),
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='habit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_record', models.IntegerField()),
                ('update_date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('habit_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='habit.habit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('habit_record', 'daily_record'), name='one_record_per_day'),
        ),
    ]
