# Generated by Django 4.0.3 on 2022-03-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_remove_result_one_record_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
    ]
