# Generated by Django 4.0.3 on 2022-03-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0015_habit_unit_alter_result_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(),
        ),
    ]
