# Generated by Django 4.0.3 on 2022-03-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0016_alter_habit_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
